@Realstate_servcices.Server_HostAddress_HTTPS = https://localhost:7075
@Realstate_servcices.Server_HostAddress_HTTP = http://localhost:1452
@ContentType = application/json

### Health Check (HTTP)
### Test with invalid data - Register agent with existing username
POST {{Realstate_servcices.Server_HostAddress_HTTPS}}/api/agent/register
Content-Type: {{ContentType}}

{
  "email": "roberto.ramirez@gmail.com",
  "username": "Ram@3000",
  "password": "Ramirez@2k13",
  "firstName": "Roberto",
  "lastName": "Ramirez",
  "cellPhoneNo": "09666627948",
  "licenseNumber": "LIC-123458"
}